"""empty message

Revision ID: 17510e9586b2
Revises: 790e43102b36
Create Date: 2021-10-14 21:59:43.109807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17510e9586b2'
down_revision = '790e43102b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quotes', 'quote_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.alter_column('quotes', 'quote_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('quotes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
