"""empty message

Revision ID: 366e678f584c
Revises: d47044a6c025
Create Date: 2021-11-08 15:44:22.277713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366e678f584c'
down_revision = 'd47044a6c025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('book_title', sa.String(), nullable=True),
    sa.Column('quote', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('quote_id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_quotes_author'), 'quotes', ['author'], unique=False)
    op.create_index(op.f('ix_quotes_book_title'), 'quotes', ['book_title'], unique=False)
    op.create_index(op.f('ix_quotes_quote'), 'quotes', ['quote'], unique=False)
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_password_hash'), 'users', ['password_hash'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_book_title'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_author'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
