"""empty message

Revision ID: 43158d5b0f11
Revises: 3782c2e2bf75
Create Date: 2021-10-14 22:17:28.380645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43158d5b0f11'
down_revision = '3782c2e2bf75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('book_title', sa.String(), nullable=True),
    sa.Column('quote', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('quote_id')
    )
    op.create_index(op.f('ix_quotes_author'), 'quotes', ['author'], unique=False)
    op.create_index(op.f('ix_quotes_book_title'), 'quotes', ['book_title'], unique=False)
    op.create_index(op.f('ix_quotes_quote'), 'quotes', ['quote'], unique=False)
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_book_title'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_author'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
