"""empty message

Revision ID: 6fb7ed1bcc5d
Revises: 62ed252ddeca
Create Date: 2021-11-19 22:26:03.653769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb7ed1bcc5d'
down_revision = '62ed252ddeca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
