"""empty message

Revision ID: 740aadfb3360
Revises: b2f49d7a3c73
Create Date: 2021-10-26 21:46:34.764007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740aadfb3360'
down_revision = 'b2f49d7a3c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
