"""empty message

Revision ID: 790e43102b36
Revises: 219f80989284
Create Date: 2021-10-14 21:52:15.554645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790e43102b36'
down_revision = '219f80989284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('book_title', sa.String(), nullable=True),
    sa.Column('quote', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_quotes_author'), 'quotes', ['author'], unique=True)
    op.create_index(op.f('ix_quotes_book_title'), 'quotes', ['book_title'], unique=True)
    op.create_index(op.f('ix_quotes_quote'), 'quotes', ['quote'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_quote'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_book_title'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_author'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
