"""empty message

Revision ID: b2f49d7a3c73
Revises: 43158d5b0f11
Create Date: 2021-10-14 22:20:54.824385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f49d7a3c73'
down_revision = '43158d5b0f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'quotes', ['quote_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='unique')
    # ### end Alembic commands ###
