"""empty message

Revision ID: ef23d9a68770
Revises: 17510e9586b2
Create Date: 2021-10-14 22:12:47.952643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef23d9a68770'
down_revision = '17510e9586b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_quotes_author'), 'quotes', ['author'], unique=True)
    op.create_index(op.f('ix_quotes_book_title'), 'quotes', ['book_title'], unique=True)
    op.create_index(op.f('ix_quotes_quote'), 'quotes', ['quote'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_quote'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_book_title'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_author'), table_name='quotes')
    # ### end Alembic commands ###
